TARGET := simpleDog

CC := g++-7
CCFLAGS := -std=c++17 -shared -fPIC -undefined dynamic_lookup
INCLUDEPATH := -I/usr/local/include/freetype2
LIBPTH :=
LIBS :=

make:
	$(CC) $(CCFLAGS) $(INCLUDEPATH) -o $(TARGET).so $(TARGET).cpp $(LIBPATH) $(LIBS)
